### ISSUE TITLE
Can't build production environment 

### ISSUE THREAD

**Issue by silagy** [kmanaseryan/ngx-envconfig#8] opened 2018-11-25 20:56 UTC
While running the command ng build --configuration=production

I am getting the following error:

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'ConfigModule' was called.

Here is the code that I am using the app.module file

`import { ConfigModule, ConfigService } from 'ngx-envconfig';

import { environment } from '../environments/environment'; // <-- add this line

const appRoutes: Routes = [
  { path: 'charts/:id', component: PiechartComponent }
];

@NgModule({
  declarations: [
    AppComponent,
    BarchartComponent,
    LinechartComponent,
    PiechartComponent
  ],
  imports: [
    BrowserModule,
    HttpModule,
    HttpClientModule,
    AmChartsModule,
    RouterModule.forRoot(appRoutes),
    ConfigModule.forRoot(environment) // <-- pass environment variable
  ],
  providers: [ServerService],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**Comment by swapnil0545** [comment] 2019-01-24 08:01
I am getting the same error. An example to fix the same will be good. @kmanaseryan

**Comment by kmanaseryan** [comment] 2019-01-25 09:32
Thanks for opening the issue. This is duplicate of Issue #4  . Please follow that one for the future updates, I just started to work on it. Thanks!

**Closed as completed by kmanaseryan** 2019-01-25 09:32 UTC
Labels: bug, duplicate

**Comment by kmanaseryan** [comment] 2019-01-25 10:18
Guys this is fixed in the Issue #4 . Thanks for letting me know.  

btw @silagy you don't have to have `ServerService` in the providers array ;)
